# -*- coding: utf-8 -*-
"""Literature edges.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6OFYOTGoEeu32aIpH5UBWkJAmnIkyRj
"""

# ============================================================
# MTB KG STARTER PIPELINE
# Parse RefSeq GFF + Protein FASTA + map genes to STRING
# ============================================================

import os
import re
import time
import requests
import pandas as pd
from io import StringIO

# Install Biopython if not already installed
try:
    from Bio import SeqIO
except ImportError:
    print("Biopython not found, installing...")
    !pip install biopython
    from Bio import SeqIO

# ------------------------------------------------------------
# 0. SET FILE PATHS
# ------------------------------------------------------------

DATA_DIR = "/content/"   # change if needed

GFF_FILE = os.path.join(DATA_DIR, "genomic.gff")
PROTEIN_FASTA = os.path.join(DATA_DIR, "protein.faa")

OUT_DIR = os.path.join(DATA_DIR, "mtb_kg_outputs")
os.makedirs(OUT_DIR, exist_ok=True)

SPECIES = 83332   # Mycobacterium tuberculosis H37Rv in STRING
CALLER_ID = "isha_mtb_kg_project"

"""## Literature Edges"""

!pip install requests pandas tqdm

import requests
import pandas as pd
from tqdm import tqdm

def get_epmc_papers(query, max_records=2000):
    base_url = "https://www.ebi.ac.uk/europepmc/webservices/rest/search"

    records = []
    page = 1
    page_size = 100

    while len(records) < max_records:
        params = {
            "query": query,
            "format": "json",
            "pageSize": page_size,
            "page": page
        }

        r = requests.get(base_url, params=params)
        data = r.json()

        results = data.get("resultList", {}).get("result", [])

        if not results:
            break

        for paper in results:
            records.append({
                "pmid": paper.get("pmid"),
                "pmcid": paper.get("pmcid"),
                "title": paper.get("title"),
                "abstract": paper.get("abstractText"),
                "year": paper.get("pubYear"),
                "journal": paper.get("journalTitle")
            })

        page += 1

        if len(records) >= max_records:
            break

    return pd.DataFrame(records)

query = '"Mycobacterium tuberculosis" AND (virulence OR secretion OR regulation)'

epmc_df = get_epmc_papers(query, max_records=2000)

print("Total papers:", len(epmc_df))
epmc_df.head()

epmc_df.to_csv("/content/mtb_kg_outputs/epmc_papers_initial.csv", index=False)

epmc_df[["pmid", "pmcid", "title", "abstract", "year"]].head(20)

print("Total papers:", len(epmc_df))
print("With abstract:", epmc_df["abstract"].notna().sum())
print("With PMCID/full text possible:", epmc_df["pmcid"].notna().sum())

"""## Keep only PMC full text papers

## Download full-text XML from PMC
"""

import requests
import time

def fetch_pmc_xml(pmcid):
    url = f"https://www.ebi.ac.uk/europepmc/webservices/rest/{pmcid}/fullTextXML"
    r = requests.get(url)

    if r.status_code == 200 and r.text.strip():
        return r.text
    return None

"""## Extract paragraphs + sentences"""

from bs4 import BeautifulSoup
import re

def extract_sentences_from_xml(xml_text):
    soup = BeautifulSoup(xml_text, "xml")

    # extract all paragraph text
    paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]

    sentences = []
    for para in paragraphs:
        sentences.extend(re.split(r'(?<=[.!?])\s+', para))

    return sentences

"""## Detect MTB genes using gene_nodes"""

gene_nodes = pd.read_csv(os.path.join(OUT_DIR, "mtb_gene_nodes.csv"))
#build alias dictionary
def collect_ids(row):
    ids = []

    if pd.notna(row["gene_id"]):
        ids.append(str(row["gene_id"]))

    if pd.notna(row["gene_name"]) and row["gene_name"]:
        ids.append(str(row["gene_name"]))

    if pd.notna(row["aliases"]) and row["aliases"]:
        ids.extend(row["aliases"].split("|"))

    return list(set([i.strip() for i in ids if i]))

gene_aliases = {
    row["gene_id"]: collect_ids(row)
    for _, row in gene_nodes.iterrows()
}

"""Gene Detection"""

import re

def find_genes_in_sentence(sentence, gene_aliases):
    found = set()
    sentence_lower = sentence.lower()

    for gene_id, aliases in gene_aliases.items():
        for alias in aliases:
            if len(alias) < 3:
                continue

            pattern = r'\b' + re.escape(alias.lower()) + r'\b'

            if re.search(pattern, sentence_lower):
                found.add(gene_id)
                break

    return list(found)

"""## Extract literature triplets"""

def classify_relation(sentence):
    s = sentence.lower()

    if any(w in s for w in ["activate", "activates", "activation"]):
        return "ACTIVATES"
    elif any(w in s for w in ["repress", "represses", "inhibit", "inhibits"]):
        return "REPRESSES"
    elif any(w in s for w in ["regulate", "regulates", "regulation"]):
        return "REGULATES"
    elif any(w in s for w in ["interact", "interaction", "bind", "binding"]):
        return "INTERACTS_WITH"
    elif any(w in s for w in ["virulence", "pathogenesis", "infection"]):
        return "ASSOCIATED_WITH_VIRULENCE"
    else:
        return "CO_MENTIONED_WITH"

"""Build edges"""

import os
import pandas as pd
from tqdm import tqdm

OUT_DIR = "/content/mtb_kg_outputs"
lit_file = os.path.join(OUT_DIR, "literature_edges.csv")

if os.path.exists(lit_file):
    old_lit = pd.read_csv(lit_file)
    done_pmcids = set(old_lit["pmcid"].dropna().astype(str))
    literature_edges = old_lit.to_dict("records")
    print("Already processed PMCIDs:", len(done_pmcids))
else:
    done_pmcids = set()
    literature_edges = []

# Use epmc_df defined earlier and filter for papers with PMCIDs
sample_papers = epmc_df[epmc_df["pmcid"].notna()].head(150)

for _, row in tqdm(sample_papers.iterrows(), total=len(sample_papers)):
    pmcid = str(row["pmcid"])

    if pmcid in done_pmcids:
        continue

    xml_text = fetch_pmc_xml(pmcid)
    if xml_text is None:
        continue

    sentences = extract_sentences_from_xml(xml_text)

    for sent in sentences:
        genes_found = find_genes_in_sentence(sent, gene_aliases)

        if len(genes_found) < 2:
            continue

        relation = classify_relation(sent)

        for i in range(len(genes_found)):
            for j in range(i + 1, len(genes_found)):
                literature_edges.append({
                    "source_gene": genes_found[i],
                    "target_gene": genes_found[j],
                    "relation": relation,
                    "evidence_text": sent,
                    "pmcid": pmcid,
                    "paper_title": row["title"],
                    "evidence_source": "literature",
                    "confidence_score": 0.6 if relation != "CO_MENTIONED_WITH" else 0.3
                })

    # save progress after every paper
    pd.DataFrame(literature_edges).to_csv(lit_file, index=False)

literature_df = pd.DataFrame(literature_edges)
print("Final literature edges:", literature_df.shape)

"""## Mount Google Drive and create folders"""

from google.colab import drive
drive.mount("/content/drive")

import os

BASE_DIR = "/content/drive/MyDrive/mtb_kg_project"
OUT_DIR = os.path.join(BASE_DIR, "outputs")
XML_CACHE_DIR = os.path.join(BASE_DIR, "xml_cache")

os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(XML_CACHE_DIR, exist_ok=True)

print("OUT_DIR:", OUT_DIR)
print("XML cache:", XML_CACHE_DIR)

"""Load gene nodes and build aliases

This uses MTB gene table to recognize Rv IDs and gene names in papers.
"""

import pandas as pd
import re
import os

gene_nodes = pd.read_csv("/content/mtb_kg_outputs/mtb_gene_nodes.csv")

gene_nodes["gene_id"] = gene_nodes["gene_id"].astype(str).str.strip()
gene_nodes["gene_name"] = gene_nodes["gene_name"].fillna("").astype(str).str.strip()
gene_nodes["aliases"] = gene_nodes["aliases"].fillna("").astype(str).str.strip()

def collect_ids(row):
    ids = []

    if row["gene_id"]:
        ids.append(row["gene_id"])

    if row["gene_name"]:
        ids.append(row["gene_name"])

    if row["aliases"]:
        ids.extend(row["aliases"].split("|"))

    # clean
    ids = [x.strip() for x in ids if x and str(x).strip()]
    ids = list(set(ids))

    # remove very short aliases because they create false positives
    ids = [x for x in ids if len(x) >= 3]

    return ids

gene_aliases = {
    row["gene_id"]: collect_ids(row)
    for _, row in gene_nodes.iterrows()
}

print("Genes with aliases:", len(gene_aliases))
print("Example:", list(gene_aliases.items())[:3])

"""Search Europe PMC for full-text papers

This version searches only papers likely to have full text and MTB gene biology
"""

import requests
import time
from tqdm import tqdm

def get_epmc_papers(query, max_records=2000, page_size=100):
    base_url = "https://www.ebi.ac.uk/europepmc/webservices/rest/search"
    records = []
    page = 1

    while len(records) < max_records:
        params = {
            "query": query,
            "format": "json",
            "pageSize": page_size,
            "page": page
        }

        r = requests.get(base_url, params=params, timeout=60)

        if r.status_code != 200:
            print("Request failed:", r.status_code, r.text[:200])
            break

        data = r.json()
        results = data.get("resultList", {}).get("result", [])

        if not results:
            break

        for paper in results:
            records.append({
                "pmid": paper.get("pmid"),
                "pmcid": paper.get("pmcid"),
                "doi": paper.get("doi"),
                "title": paper.get("title"),
                "abstract": paper.get("abstractText"),
                "year": paper.get("pubYear"),
                "journal": paper.get("journalTitle"),
                "authorString": paper.get("authorString"),
                "citedByCount": paper.get("citedByCount"),
                "isOpenAccess": paper.get("isOpenAccess"),
                "inEPMC": paper.get("inEPMC"),
                "hasFullText": paper.get("hasFullText")
            })

            if len(records) >= max_records:
                break

        page += 1
        time.sleep(0.2)

    df = pd.DataFrame(records)
    return df.drop_duplicates(subset=["pmcid", "pmid", "title"])

query_broad = (
   '"Mycobacterium tuberculosis" AND HAS_FT:Y'
)

epmc_df = get_epmc_papers(query_broad, max_records=2000)

print("Total records:", epmc_df.shape)
print("With PMCID:", epmc_df["pmcid"].notna().sum())
print("Journals:")
print(epmc_df["journal"].value_counts().head(20))

epmc_df.to_csv(os.path.join(OUT_DIR, "epmc_papers_broad_2000.csv"), index=False)
epmc_df.head()

query_high_impact = (
    '"Mycobacterium tuberculosis" '
    'AND HAS_FT:Y '
    'AND (JOURNAL:"Nature" OR JOURNAL:"Science" OR JOURNAL:"Cell" '
    'OR JOURNAL:"Nature Communications" OR JOURNAL:"Nature Microbiology" '
    'OR JOURNAL:"Proceedings of the National Academy of Sciences of the United States of America" '
    'OR JOURNAL:"PLOS Pathogens" OR JOURNAL:"mBio" OR JOURNAL:"Nucleic Acids Research")'
)

epmc_hi = get_epmc_papers(query_high_impact, max_records=500)

print("High-impact records:", epmc_hi.shape)
print(epmc_hi["journal"].value_counts())

epmc_hi.to_csv(os.path.join(OUT_DIR, "epmc_papers_high_impact.csv"), index=False)
epmc_hi.head()

epmc_all = pd.concat([
    epmc_hi.assign(priority="high_impact"),
    epmc_df.assign(priority="broad")
], ignore_index=True)

epmc_all = epmc_all.drop_duplicates(subset=["pmcid"])
epmc_all = epmc_all[epmc_all["pmcid"].notna()].copy()

print("Combined PMCID papers:", epmc_all.shape)
print(epmc_all["priority"].value_counts())

epmc_all.to_csv(os.path.join(OUT_DIR, "epmc_papers_selected.csv"), index=False)

"""Cache XML files locally/Drive"""

def safe_filename(pmcid):
    return str(pmcid).replace("/", "_").replace("\\", "_")

def xml_cache_path(pmcid):
    return os.path.join(XML_CACHE_DIR, f"{safe_filename(pmcid)}.xml")

def fetch_and_cache_pmc_xml(pmcid, sleep_time=0.2):
    path = xml_cache_path(pmcid)

    # If already downloaded, read from cache
    if os.path.exists(path) and os.path.getsize(path) > 100:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            return f.read(), "cached"

    url = f"https://www.ebi.ac.uk/europepmc/webservices/rest/{pmcid}/fullTextXML"

    try:
        r = requests.get(url, timeout=90)

        if r.status_code == 200 and r.text.strip():
            with open(path, "w", encoding="utf-8") as f:
                f.write(r.text)

            time.sleep(sleep_time)
            return r.text, "downloaded"

        return None, f"failed_status_{r.status_code}"

    except Exception as e:
        return None, f"error_{type(e).__name__}"

def cache_xml_batch(papers_df, n_papers=300):
    papers = papers_df.head(n_papers).copy()

    log = []

    for _, row in tqdm(papers.iterrows(), total=len(papers)):
        pmcid = row["pmcid"]
        xml_text, status = fetch_and_cache_pmc_xml(pmcid)

        log.append({
            "pmcid": pmcid,
            "status": status,
            "xml_length": len(xml_text) if xml_text else 0,
            "journal": row.get("journal", ""),
            "title": row.get("title", "")
        })

        # save log frequently
        pd.DataFrame(log).to_csv(os.path.join(OUT_DIR, "xml_cache_log.csv"), index=False)

    return pd.DataFrame(log)

xml_log = cache_xml_batch(epmc_all, n_papers=2000)

print(xml_log["status"].value_counts())
xml_log.head()

epmc_all["pmcid"].nunique()

"""Parse XML into sentences"""

from bs4 import BeautifulSoup

def extract_sentences_from_xml(xml_text):
    soup = BeautifulSoup(xml_text, "xml")

    # remove references because they often contain many gene-like false positives
    for tag in soup.find_all(["ref-list", "table-wrap", "fig"]):
        tag.decompose()

    paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]

    sentences = []
    for para in paragraphs:
        para = re.sub(r"\s+", " ", para).strip()
        if not para:
            continue

        # simple sentence split
        parts = re.split(r'(?<=[.!?])\s+', para)
        sentences.extend([s.strip() for s in parts if len(s.strip()) > 40])

    return sentences

"""Gene detection and relation classification"""

def find_genes_in_sentence(sentence, gene_aliases):
    found = set()
    s = sentence.lower()

    for gene_id, aliases in gene_aliases.items():
        for alias in aliases:
            alias_l = alias.lower().strip()

            if len(alias_l) < 3:
                continue

            pattern = r"\b" + re.escape(alias_l) + r"\b"

            if re.search(pattern, s):
                found.add(gene_id)
                break

    return sorted(found)

def classify_relation(sentence):
    s = sentence.lower()

    # order matters: stronger/specific relations first
    if any(w in s for w in [
        "activates", "activated", "activation", "upregulates", "up-regulates",
        "induces", "induced", "enhances", "increases"
    ]):
        return "ACTIVATES"

    if any(w in s for w in [
        "represses", "repressed", "repression", "inhibits", "inhibited",
        "suppresses", "suppressed", "diminishes", "decreases", "reduces"
    ]):
        return "REPRESSES"

    if any(w in s for w in [
        "regulates", "regulated", "regulation", "regulator", "controls",
        "modulates", "modulated"
    ]):
        return "REGULATES"

    if any(w in s for w in [
        "interacts", "interaction", "interacted", "binds", "binding",
        "bound to", "complex", "associates with"
    ]):
        return "INTERACTS_WITH"

    if any(w in s for w in [
        "virulence", "pathogenesis", "pathogenicity", "infection",
        "infectivity", "host", "macrophage"
    ]):
        return "ASSOCIATED_WITH_VIRULENCE"

    return "CO_MENTIONED_WITH"

relation_weights = {
    "CO_MENTIONED_WITH": 0.3,
    "ASSOCIATED_WITH_VIRULENCE": 0.6,
    "INTERACTS_WITH": 0.7,
    "REGULATES": 0.8,
    "ACTIVATES": 0.9,
    "REPRESSES": 0.9
}

"""Extract literature edges from cached XML"""

def extract_edges_from_cached_xml(papers_df, n_papers=300, save_every=10):
    out_file = os.path.join(OUT_DIR, f"literature_edges_scaled_{n_papers}.csv")
    progress_file = os.path.join(OUT_DIR, f"literature_progress_{n_papers}.csv")

    # Resume existing edges if file exists
    if os.path.exists(out_file):
        literature_df = pd.read_csv(out_file)
        literature_edges = literature_df.to_dict("records")
        processed = set(literature_df["pmcid"].dropna().astype(str))
        print("Resuming. Existing edges:", len(literature_edges))
        print("Already processed PMCIDs:", len(processed))
    else:
        literature_edges = []
        processed = set()

    papers = papers_df.head(n_papers).copy()

    paper_log = []

    for idx, row in tqdm(papers.iterrows(), total=len(papers)):
        pmcid = str(row["pmcid"])

        if pmcid in processed:
            continue

        path = xml_cache_path(pmcid)

        if not os.path.exists(path):
            # Try downloading if missing
            xml_text, status = fetch_and_cache_pmc_xml(pmcid)
        else:
            with open(path, "r", encoding="utf-8", errors="ignore") as f:
                xml_text = f.read()
            status = "cached"

        if not xml_text:
            paper_log.append({
                "pmcid": pmcid,
                "status": "no_xml",
                "edges": 0
            })
            continue

        sentences = extract_sentences_from_xml(xml_text)

        paper_edge_count = 0

        for sent in sentences:
            # sentence quality filter
            if len(sent) > 1200:
                continue

            genes_found = find_genes_in_sentence(sent, gene_aliases)

            if len(genes_found) < 2:
                continue

            # optional: reduce very noisy sentences
            if len(genes_found) > 8:
                continue

            relation = classify_relation(sent)
            score = relation_weights.get(relation, 0.3)

            for i in range(len(genes_found)):
                for j in range(i + 1, len(genes_found)):
                    literature_edges.append({
                        "source_gene": genes_found[i],
                        "relation": relation,
                        "target_gene": genes_found[j],
                        "evidence_source": "literature",
                        "score": score,
                        "confidence_score": score,
                        "is_directed": relation in ["REGULATES", "ACTIVATES", "REPRESSES", "ASSOCIATED_WITH_VIRULENCE"],
                        "evidence_text": sent,
                        "pmid": row.get("pmid", ""),
                        "pmcid": pmcid,
                        "doi": row.get("doi", ""),
                        "paper_title": row.get("title", ""),
                        "journal": row.get("journal", ""),
                        "year": row.get("year", ""),
                        "priority": row.get("priority", "")
                    })
                    paper_edge_count += 1

        processed.add(pmcid)

        paper_log.append({
            "pmcid": pmcid,
            "status": status,
            "sentences": len(sentences),
            "edges": paper_edge_count,
            "journal": row.get("journal", ""),
            "title": row.get("title", "")
        })

        # save progress
        if len(processed) % save_every == 0:
            temp_df = pd.DataFrame(literature_edges)
            temp_df.to_csv(out_file, index=False)

            pd.DataFrame(paper_log).to_csv(progress_file, index=False)

    literature_df = pd.DataFrame(literature_edges)

    # clean
    if not literature_df.empty:
        literature_df = literature_df[literature_df["source_gene"] != literature_df["target_gene"]]
        literature_df = literature_df.drop_duplicates(
            subset=["source_gene", "relation", "target_gene", "pmcid", "evidence_text"]
        )

    literature_df.to_csv(out_file, index=False)
    pd.DataFrame(paper_log).to_csv(progress_file, index=False)

    print("Saved:", out_file)
    print("Final edges:", literature_df.shape)

    return literature_df, pd.DataFrame(paper_log)

literature_df_300, log_300 = extract_edges_from_cached_xml(epmc_all, n_papers=300)

print(literature_df_300["relation"].value_counts())
print("Unique papers with edges:", literature_df_300["pmcid"].nunique())
print("Unique journals:", literature_df_300["journal"].nunique())

literature_df_300.head()

def journal_summary(literature_df):
    return (
        literature_df.groupby("journal")
        .agg(
            n_edges=("relation", "count"),
            n_papers=("pmcid", "nunique"),
            n_genes_source=("source_gene", "nunique"),
            n_genes_target=("target_gene", "nunique")
        )
        .sort_values("n_edges", ascending=False)
        .reset_index()
    )

journal_stats = journal_summary(literature_df_300)
journal_stats.head(30)

high_impact_keywords = [
    "Nature", "Science", "Cell", "PNAS", "Proceedings of the National Academy",
    "PLOS Pathogens", "mBio", "Nucleic Acids Research"
]

hi_edges = literature_df_300[
    literature_df_300["journal"].fillna("").str.contains(
        "|".join(high_impact_keywords),
        case=False,
        na=False
    )
]

print("High-impact literature edges:", hi_edges.shape)
print(hi_edges["journal"].value_counts())
hi_edges.head()

# Abstracts
import os
import re
import time
import requests
import pandas as pd
from tqdm import tqdm

OUT_DIR = "/content/mtb_kg_outputs"
os.makedirs(OUT_DIR, exist_ok=True)

def get_epmc_abstract_papers(query, max_records=3000, page_size=100):
    base_url = "https://www.ebi.ac.uk/europepmc/webservices/rest/search"
    records = []
    page = 1

    while len(records) < max_records:
        params = {
            "query": query,
            "format": "json",
            "pageSize": page_size,
            "page": page,
            "resultType": "core"
        }

        r = requests.get(base_url, params=params, timeout=60)
        data = r.json()

        results = data.get("resultList", {}).get("result", [])
        if not results:
            break

        for paper in results:
            records.append({
                "pmid": paper.get("pmid"),
                "pmcid": paper.get("pmcid"),
                "doi": paper.get("doi"),
                "title": paper.get("title"),
                "abstract": paper.get("abstractText"),
                "year": paper.get("pubYear"),
                "journal": paper.get("journalTitle"),
                "authorString": paper.get("authorString"),
                "citedByCount": paper.get("citedByCount")
            })

            if len(records) >= max_records:
                break

        page += 1
        time.sleep(0.2)

    df = pd.DataFrame(records)

    print("Before abstract filtering:", df.shape)
    print("With abstract:", df["abstract"].notna().sum())

    df = df[df["abstract"].notna()].copy()
    df = df[df["abstract"].astype(str).str.len() > 50].copy()
    df = df.drop_duplicates(subset=["pmid", "title"])

    return df

query_abstract = 'Mycobacterium tuberculosis'

abstract_df = get_epmc_abstract_papers(query_abstract, max_records=3000)

print("Abstract papers:", abstract_df.shape)
abstract_df[["pmid", "title", "abstract", "year", "journal"]].head()

# sentence spilt

def split_sentences(text):
    text = str(text)
    text = re.sub(r"\s+", " ", text).strip()
    return re.split(r'(?<=[.!?])\s+', text)

# extract abstract literature edges
relation_weights = {
    "CO_MENTIONED_WITH": 0.2,
    "ASSOCIATED_WITH_VIRULENCE": 0.5,
    "INTERACTS_WITH": 0.6,
    "REGULATES": 0.7,
    "ACTIVATES": 0.8,
    "REPRESSES": 0.8
}

directed_relations = {
    "REGULATES",
    "ACTIVATES",
    "REPRESSES",
    "ASSOCIATED_WITH_VIRULENCE"
}

abstract_edges = []

for _, row in tqdm(abstract_df.iterrows(), total=len(abstract_df)):
    abstract = row["abstract"]
    sentences = split_sentences(abstract)

    for sent in sentences:
        if len(sent) < 40 or len(sent) > 1000:
            continue

        genes_found = find_genes_in_sentence(sent, gene_aliases)

        if len(genes_found) < 2:
            continue

        # avoid very noisy sentences
        if len(genes_found) > 8:
            continue

        relation = classify_relation(sent)
        score = relation_weights.get(relation, 0.2)

        for i in range(len(genes_found)):
            for j in range(i + 1, len(genes_found)):
                abstract_edges.append({
                    "source_gene": genes_found[i],
                    "relation": relation,
                    "target_gene": genes_found[j],
                    "evidence_source": "literature_abstract",
                    "score": score,
                    "confidence_score": score,
                    "is_directed": relation in directed_relations,
                    "evidence_text": sent,
                    "pmid": row.get("pmid", ""),
                    "pmcid": row.get("pmcid", ""),
                    "doi": row.get("doi", ""),
                    "paper_title": row.get("title", ""),
                    "journal": row.get("journal", ""),
                    "year": row.get("year", "")
                })

abstract_edges_df = pd.DataFrame(abstract_edges)

OUT_DIR = "/content/drive/MyDrive/mtb_kg_project/outputs"

# Save the abstract edges to a CSV file
abstract_edges_df.to_csv(os.path.join(OUT_DIR, "literature_abstract_edges.csv"), index=False)

print("Raw abstract edges:", abstract_edges_df.shape)
abstract_edges_df.head()

# combine both edges
OUT_DIR = "/content/drive/MyDrive/mtb_kg_project/outputs"

fulltext_file = os.path.join(OUT_DIR, "literature_edges_scaled_300.csv")
abstract_file = os.path.join(OUT_DIR, "literature_abstract_edges.csv")

fulltext_lit = pd.read_csv(fulltext_file)
abstract_lit = pd.read_csv(abstract_file)

# align columns
all_cols = sorted(set(fulltext_lit.columns).union(set(abstract_lit.columns)))

for col in all_cols:
    if col not in fulltext_lit.columns:
        fulltext_lit[col] = ""
    if col not in abstract_lit.columns:
        abstract_lit[col] = ""

fulltext_lit = fulltext_lit[all_cols]
abstract_lit = abstract_lit[all_cols]

literature_all = pd.concat([fulltext_lit, abstract_lit], ignore_index=True)

literature_all = literature_all.drop_duplicates(
    subset=["source_gene", "relation", "target_gene", "evidence_text"]
)

literature_all.to_csv(
    os.path.join(OUT_DIR, "literature_edges_fulltext_plus_abstracts.csv"),
    index=False
)

print("Combined literature edges:", literature_all.shape)
print(literature_all["evidence_source"].value_counts())
print(literature_all["relation"].value_counts())